id: IEEAAB626
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-10T08:47:14+00:00'
last_modified: '2022-06-15T14:07:23.664415+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13001
  title: བསྙུང་གནས་ཀྱི་རྣམ་བཤད་དང་ཕན་ཡོན་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    439B:
      image_group_id: I1KG13066
      title: Volume 1 of bsnyung gnas kyi rnam bshad dang phan yon skor phyogs bsgrigs/
      total_pages: 408
      order: 1
      base_file: 439B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
